---

- name: MY FIRST PLAYBOOK
  hosts: north 
  gather_facts: false
  connection: network_cli

  tasks:
    - name: "OSPF CONFIG"
      cisco.ios.ios_config:
        lines:
          - router-id 1.1.1.1
        parents:
          - router ospf 1
      register: my_output

    #debug: var=my_output
    - debug: var=my_output