---
- name: "PLAYBOOK TO TEST CONDITIONAL LOGIC"
  hosts: usa 
  gather_facts: true
  connection: network_cli

  tasks: 
    - name: "TASK 1"
      debug:
        msg: "Interface {{ item.key }} has an IP address of {{ item.value.ipv4.0.address }}"
      loop: "{{ ansible_facts.net_interfaces | dict2items }}"
      when: item.value.lineprotocol == "up"
      # or 
      #when: item.value.ipv4 != [] 
